---
- name: Tweak kernel configuration for performance
  copy: src=sysctl.conf
        dest=/etc/sysctl.conf
        owner=root
        group=root
        mode=0644
  notify:
    - reload-sysctl
  tags:
    - sysctl

- name: Load new sysctl values
  command: /sbin/sysctl -p
